"""Add writer bio column

Revision ID: 452674ecb94f
Revises: 3fe1f0696fe2
Create Date: 2020-02-16 14:26:39.729869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '452674ecb94f'
down_revision = '3fe1f0696fe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('writers', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('writers', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('writers', 'profile_pic_path')
    op.drop_column('writers', 'bio')
    # ### end Alembic commands ###
