"""Change column for writer/blog relstionship again

Revision ID: d9226fe9409d
Revises: 462e88986d6a
Create Date: 2020-02-16 16:02:00.010129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9226fe9409d'
down_revision = '462e88986d6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('writer_blog', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blogs', 'writers', ['writer_blog'], ['id'])
    op.drop_constraint('writers_blog_fkey', 'writers', type_='foreignkey')
    op.drop_column('writers', 'blog')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('writers', sa.Column('blog', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('writers_blog_fkey', 'writers', 'blogs', ['blog'], ['id'])
    op.drop_constraint(None, 'blogs', type_='foreignkey')
    op.drop_column('blogs', 'writer_blog')
    # ### end Alembic commands ###
